library(grid)
library(digest)
library(here)
here::i_am("R/render_pollslive_assets.R")
output_dir <- here::here("pollslive", "assets")
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
colours <- c(parchment="#F4F1EC", graphite="#2E2E2E", olive="#8A8A8A", indigo="#5D2890", orange="#F3A712", white="#FFFFFF", light="#F0EDE8")
open_card <- function(filename) {
  grDevices::png(here::here(output_dir, filename), width=1600, height=900, res=160, type="cairo", bg=colours[["parchment"]])
  grid.newpage()
}
close_card <- function() grDevices::dev.off()
draw_title <- function(text) grid.text(text, x=unit(0.07,"npc"), y=unit(0.88,"npc"), just="left", gp=gpar(col=colours[["indigo"]], fontsize=34, fontface="bold"))
draw_panel <- function(y=0.48, height=0.48) grid.roundrect(x=0.5,y=y,width=0.86,height=height,r=unit(0.025,"npc"),gp=gpar(fill=colours[["white"]],col=colours[["light"]],lwd=2))

data(iris)
data_kosatce <- data.frame(sirka_listku=iris$Petal.Width, delka_listku=iris$Petal.Length)
mod_listky <- lm(delka_listku ~ sirka_listku, data=data_kosatce)
sklon <- unname(coef(mod_listky)[["sirka_listku"]])
stopifnot(identical(round(sklon,2),2.23))
open_card("l03-formula-roles.png")
draw_title("Vzorec lineárního modelu")
draw_panel()
grid.text("delka_listku  ~  sirka_listku", y=unit(0.58,"npc"), gp=gpar(col=colours[["graphite"]],fontsize=34,fontfamily="mono",fontface="bold"))
close_card()
open_card("l03-slope-estimate.png")
draw_title("Odhad sklonu modelu")
draw_panel()
grid.text("2,23 cm / cm", y=unit(0.59,"npc"), gp=gpar(col=colours[["indigo"]],fontsize=48,fontface="bold"))
close_card()
residual <- here::here(output_dir,"l03-residual-example.png")
stopifnot(file.exists(residual), identical(digest(file=residual,algo="sha256"),"776c7693fb13dc0120217c118c8c0b18b88c58e9443534d14b4bac6dba73fbac"))
